version: '3.9'
services:
  db-pg:
    container_name: db-pg
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mevo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
